# Экран блокировки
background {
        monitor =
        path = /home/event/.config/hypr/wallpaper/toxic_regera.png
        #color =
        blur_passes = 2
        blur_size = 7
        contrast = 0.8916
        brightness = 0.8172
        vibrancy = 0.1696
        vibrancy_darkness = 0.05
}

label {
        monitor = eDP-1
        text = cmd[update:1000] echo "$(date +"%A, %d %B")"
        color = rgba(82, 255, 0, 0.9) # Acid Neon
        font_size = 30
        font_family = JetBrains Mono
        shadow_passes = 2
        shadow_size = 3
        shadow_color = rgb(18, 43, 16) # Deep Forest (Теневой зеленый)
        shadow_boost = 0.9

        position = 0, 170
        halign = center
        valign = center
}

label {
        monitor = eDP-1
        text = $TIME
        color = rgba(82, 255, 0, 0.9) # Acid Neon
        font_size = 110
        font_family = JetBrains Mono
        shadow_passes = 2
        shadow_size = 3
        shadow_color = rgb(18, 43, 16) # Deep Forest
        shadow_boost = 0.9

        position = 0, 50
        halign = center
        valign = center
}

input-field {
        monitor = eDP-1
        size = 250, 60
        rounding = -1
        outline_thickness = 2
        dots_size = 0.25
        dots_spacing = 0.35
        dots_center = true
        #dots_text_format = A
        placeholder_text = <span foreground="##52ff00">???AND???</span>
        fail_text = MAGICAL
        fail_color = rgba(255, 0, 0, 0.9) # Красный для ошибки оставил
        outer_color = rgba(10, 15, 10, 0.5) # Night Highway (Почти черный)
        inner_color = rgba(20, 40, 20, 0.5) # Тёмно-зелёная смола
        font_color = rgba(82, 255, 0, 0.9) # Acid Neon для точек пароля
        font_family = JetBrains Mono
        check_color = rgb(170, 255, 170) # Светло-зеленый при проверке
        fade_timeout = 20000

        position = 0, -300
        halign = center
        valign = center
}
